### ISSUE TITLE
Will the pretrained model will be released?

### ISSUE THREAD

**Issue by phoenixhuawei** [xg416/DATUM#1]
Thanks for the sharing of your excellent work！
BTW, will the pretrained model will be released later?
best regards

**Comment by xg416** [comment]
Thanks for reaching out!
We will release pre-trained models, the updated code and the camera ready version of this paper within this month.

**Comment by phoenixhuawei** [comment]
> Thanks for reaching out! We will release pre-trained models, the updated code and the camera ready version of this paper within this month.

Thanks for your reply, looking forward to the updates.

**Comment by WanZhonghua** [comment]
> Thanks for reaching out! We will release pre-trained models, the updated code and the camera ready version of this paper within this month.
Thank you for providing such an excellent atmospheric turbulence image repair algorithm!
When will you consider updating the training code and weights for static image restoration? Looking forward to your replies and updates!

**Comment by xg416** [comment]
Tons of deadlines hit me recently, but the update will be in 3 days

**Comment by WanZhonghua** [comment]
非常感谢！提前祝您假期愉快




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XG ***@***.***&gt;; 
发送时间: 2024年4月1日(星期一) 晚上9:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xg416/DATUM] Will the pretrained model will be released? (Issue #1)














 
Tons of deadlines hit me recently, but the update will be in 3 days
