### ISSUE TITLE
Is there another access of dataset?

### ISSUE THREAD

**Issue by NikonD850** [xg416/DATUM#2]
Dear author,
Sorry to bother you. I really appreaciate your work and want to try it on my own. I tried to download the ATSyn_static dataset for a whole day, but I stiil stuck in the trouble of network error. Could you please upload the dataset in a new drive in your convenience?

Thankfully,
Davis.

**Comment by xg416** [comment]
Hi, thanks for your attention to our work. 

It is unclear to me what the root reason for the network error is. 
If you are not in the US, you can try a VPN. If the connection between your local network and the Purdue server is unstable, you can try to save the dataset to a remote server that has a stable connection to both your local network and the Purdue server. If it is the problem of Purdue's server, other people will have the same problem and I can wait for more information raised by others.

Sadly, I don't have another convenient place to put this dataset now.

**Comment by BBuniverse** [comment]
Hi, just wondering where can we find the train_info.json and test_info.json for make_lmdb.py and train_DATUM_dynamic.py?

Thanks in advance.

**Comment by NikonD850** [comment]
> Hi, thanks for your attention to our work.
> 
> It is unclear to me what the root reason for the network error is. If you are not in the US, you can try a VPN. If the connection between your local network and the Purdue server is unstable, you can try to save the dataset to a remote server that has a stable connection to both your local network and the Purdue server. If it is the problem of Purdue's server, other people will have the same problem and I can wait for more information raised by others.
> 
> Sadly, I don't have another convenient place to put this dataset now.
