### ISSUE TITLE
Related Project Question

### ISSUE THREAD

**Issue by NikonD850** [xg416/DATUM#4]
Dear author,
Thanks for your detailed reply in #2 issue & sorry to interrupt again. Could you please release the dataset and the test code of your previous work PiRN? No one seems to be responding the issues of the project.

Thanks in advance,
Davis.

**Comment by xg416** [comment]
It is stored in the server at UT Austin, I can contact Ajay about that

**Comment by NikonD850** [comment]
> It is stored in the server at UT Austin, I can contact Ajay about that

Thanks for your reply! Looking forward for the release!

**Comment by xg416** [comment]
I suppose you are Hua Tong who has requested the dataset via email recently, and I hope Ajay's reply helps.

**Comment by NikonD850** [comment]
> I suppose you are Hua Tong who has requested the dataset via email recently, and I hope Ajay's reply helps.

Sorry but I'm not the guy : |
Can I get a copy of "reply"? My email address is nikoncopd850@gmail.com.

Thx,
Davis

**Comment by xg416** [comment]
sure
