### ISSUE TITLE
How to train?

### ISSUE THREAD

**Issue by jcy512** [xg416/DATUM#5]
I am very interested in your research. May I ask how many GPUs you have and what model of GPUs are used for training?

**Comment by xg416** [comment]
We used 2 A100-80G. Initially, you can use 24 frames for training, and the batch size is 8; in the last 400000 iterations, we used 30 frames and reduced the batch size to 6. To train on the ATSyn-static, we used 36 frames and batch size 4.

**Comment by jcy512** [comment]
How long does it take for you to train once? I have four NVIDIA 3090Ti graphics cards. I'm not sure if I can use them for training.

**Comment by jcy512** [comment]
Each graphics card has 24G memory. I am very grateful for your help.

**Comment by jcy512** [comment]
> We used 2 A100-80G. Initially, you can use 24 frames for training, and the batch size is 8; in the last 400000 iterations, we used 30 frames and reduced the batch size to 6. To train on the ATSyn-static, we used 36 frames and batch size 4.

Could you please tell me how long it takes to train a dynamic dataset and a static dataset respectively? I am very grateful for your help with my previous question.

**Comment by xg416** [comment]
We used 30 days to train on the dynamic scene data and another 20 days for the static scene data.

**Comment by jcy512** [comment]
> We used 30 days to train on the dynamic scene data and another 20 days for the static scene data.

Once again, thank you for your response. Due to our hardware limitations, we are unable to conduct tests on the ATSyn dataset. Could you please provide information on the training strategy and duration for DATUM on the TMT dataset?

**Comment by xg416** [comment]
You just need to replace ATSyn's dataloader with TMT's dataloader. Another important difference is that the tilt-removal decoder of DATUM warps the tilt-only image to the ground truth image, while there's no tilt-only image in TMT's dataset. You can warp the input turbulence image to the blur-only image instead.
The scale of the ATSyn dataset is roughly the same as that of TMT's dataset.
The test on the ATSyn dataset can be done on 12 or 24-GB GPUs because you just need batch size 1. I assume you are saying you are unable to conduct **training** right?

**Comment by jcy512** [comment]
> 您只需要将 ATSyn 的数据加载器替换为 TMT 的数据集即可。 另一个重要的区别是，DATUM 的倾斜消除解码器将仅倾斜图像扭曲为地面真实图像，而 TMT 数据集中没有仅倾斜图像。 您可以将输入湍流图像扭曲为仅模糊图像。 ATSyn数据集的规模与TMT数据集的规模大致相同。 ATSyn 数据集上的测试可以在 12 或 24 GB GPU 上完成，因为您只需要批量大小 1。我假设您是说您无法进行 **训练， **对吗？

Yes, I was wondering about how to train the model, but you mentioned that the scale of the ATSyn dataset is roughly the same as that of the TMT dataset. However, I am quite confused when downloading them. Why is the capacity of TMT_static 49.6G, while the capacity of ATSyn-static is 117G? The TMT_static dataset contains 9017 sequences, with each sequence having 101 images, including 50 blurred images, 50 turbulent images, and 1 clear image. In your paper, you mentioned that the ATSyn-static dataset only has 3000 sequences, and each sequence contains the same number of images as the TMT_static dataset. Why is there such a large difference in the memory capacity of the two datasets?

**Comment by xg416** [comment]
"Yes, I was wondering about how to train the model, but you mentioned that the scale of the ATSyn dataset is roughly the same as that of the TMT dataset. "
This is not correct; I replied, "You just need to replace ATSyn's dataloader with TMT's dataloader. Another important difference is that the tilt-removal decoder of DATUM warps the tilt-only image to the ground truth image, while there's no tilt-only image in TMT's dataset.  You can warp the input turbulence image to the blur-only image instead." I exactly answered your question.

"The scale of the ATSyn dataset is roughly the same as that of TMT's dataset." This means you will need the same time and resources to train on the TMT dataset, and the training strategy is the same except for the modality difference I mentioned above.

"Why is there such a large difference in the memory capacity of the two datasets?"
This is simple: We think 2000 training sequences are enough to achieve good generalization capability on the currently available real-world images.

**Comment by jcy512** [comment]
Thank you for your previous answer. As the ATSyn dataset is too large, I haven't downloaded it yet. So I'd like to know why the 9017 sequences in the TMT_static dataset are 49GB in size, while the 3000 sequences in the ATSyn_static dataset are 117GB in size.

**Comment by xg416** [comment]
ATSyn_static uses PNG format while the other uses JPEG
